module Logic.SeqScanDetector
  ( detectSeqScans,
    generateCreateIndexStatements,
    extractFilterColumns,
  )
where

import Base.Prelude
import Data.Text qualified as Text
import Logic.Algebra (SeqScanFinding (..))

-- | Detect sequential scans with filters from EXPLAIN text output lines.
-- Only seq scans that have a filter condition are flagged,
-- because those indicate a missing index. Full table scans without
-- a filter are expected for queries that need all rows.
detectSeqScans :: [Text] -> [SeqScanFinding]
detectSeqScans = go
  where
    go [] = []
    go [_] = []
    go (line : nextLine : rest)
      | Just (indent, tableName) <- parseSeqScanLine line,
        Just condition <- parseFilterLine indent nextLine =
          let columns = extractFilterColumns condition
           in SeqScanFinding {tableName, filterCondition = condition, suggestedIndexColumns = columns}
                : go rest
      | otherwise = go (nextLine : rest)

-- | Parse a line for "Seq Scan on <table>" pattern.
-- Returns the indentation level and table name.
parseSeqScanLine :: Text -> Maybe (Int, Text)
parseSeqScanLine line =
  let indent = Text.length (Text.takeWhile (== ' ') line)
      trimmed = Text.strip line
      -- Remove plan tree arrow prefix if present (e.g., "->  ")
      withoutArrow = case Text.stripPrefix "-> " trimmed of
        Just rest -> Text.stripStart rest
        Nothing -> trimmed
   in case Text.stripPrefix "Seq Scan on " withoutArrow of
        Just rest ->
          let tableName = Text.takeWhile (\c -> c /= ' ' && c /= '(') rest
           in if Text.null tableName then Nothing else Just (indent, tableName)
        Nothing -> Nothing

-- | Parse a Filter line that is a child of a parent node.
-- The line must be indented more than the parent.
parseFilterLine :: Int -> Text -> Maybe Text
parseFilterLine parentIndent line =
  let indent = Text.length (Text.takeWhile (== ' ') line)
      trimmed = Text.strip line
   in if indent > parentIndent
        then Text.stripPrefix "Filter: " trimmed
        else Nothing

-- | Extract column names from a filter condition.
-- Handles common patterns like:
-- - @(format = $1)@
-- - @((id = $1) AND (name = $2))@
-- - @(album_artist.artist = $1)@
extractFilterColumns :: Text -> [Text]
extractFilterColumns condition =
  let subExprs = splitOnKeywords condition
   in nub (mapMaybe extractFirstColumn subExprs)
  where
    splitOnKeywords text =
      text
        & Text.replace " AND " "\0"
        & Text.replace " OR " "\0"
        & Text.splitOn "\0"

    extractFirstColumn expr =
      let cleaned = Text.dropWhile (\c -> c == '(' || c == ' ') expr
          ident = Text.takeWhile (\c -> isAlphaNum c || c == '_' || c == '.') cleaned
       in if Text.null ident
            || Text.isPrefixOf "$" ident
            || Text.toUpper ident `elem` ["NOT", "IS", "NULL", "TRUE", "FALSE", "ANY", "ALL"]
            then Nothing
            else Just (extractColumnPart ident)

    -- For qualified names "table.column", take just "column".
    extractColumnPart ident =
      case Text.splitOn "." ident of
        [_table, col] -> col
        _ -> ident

-- | Generate CREATE INDEX SQL statements from seq-scan findings.
generateCreateIndexStatements :: [SeqScanFinding] -> Text
generateCreateIndexStatements findings =
  Text.unlines
    ( "-- Auto-generated by pgenie: indexes to optimize sequential scans"
        : map generateIndex findings
    )
  where
    generateIndex finding =
      if null finding.suggestedIndexColumns
        then "-- TODO: Create index on " <> finding.tableName <> " for filter: " <> finding.filterCondition
        else "CREATE INDEX ON " <> finding.tableName <> " (" <> Text.intercalate ", " finding.suggestedIndexColumns <> ");"
