flowchart TD

cli-app --> v1-project-file
cli-app --> generator
generator --> v1-hasql-hs-generator
generator --> v1-jdbc-java-generator
generator --> app-algebra
cli-app --> introspector
cli-app--> v1-sig-file
cli-app --> command-cli-app-framework
v1-project-file --> app-algebra
v1-hasql-hs-generator --> gen-algebra
v1-jdbc-java-generator --> gen-algebra
app-algebra --> gen-algebra
v1-sig-file --> app-algebra
introspector --> app-algebra
cli-app --> app-algebra

subgraph generators
  direction TB
  v1-hasql-hs-generator
  v1-jdbc-java-generator
end

subgraph integrations
  direction TB
  generator
  introspector
  v1-sig-file
  v1-project-file

end

