flowchart LR

cli-app ---> engine
generator --> generators
generator --> app-algebra
v1-project-file --> app-algebra
v1-hasql-hs-generator --> gen-algebra
v1-jdbc-java-generator --> gen-algebra
app-algebra --> gen-algebra
v1-sig-file --> app-algebra
introspector --> app-algebra
cli-algebra --> app-algebra
cli-app --> cli-algebra

subgraph generators
  v1-hasql-hs-generator
  v1-jdbc-java-generator
end

subgraph engine[Implementation of services required for algebra exposing a single program]
  generator
  introspector
  v1-sig-file
  v1-project-file
end
