%% Hierarchy of logic components

flowchart TD

App --> Queries
App --> Migrations
App --> ProjectFile
App --> Generation

Queries --> FileSystem
Queries --> Generation
Queries --> Database

Migrations --> FileSystem
Migrations --> Database

ProjectFile --> FileSystem

