name: PR Validation

on:
  pull_request:

concurrency:
  group: pr-validation
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      qc-max-success: 1000
